@url = http://localhost:5000



###


GET {{url}}/reservations

###


GET {{url}}/reservations/f649abd5-8934-44fe-85ce-ae1008c61b99

###

POST {{url}}/reservations
Content-Type: application/json

{
    "parkingSpotId": "00000000-0000-0000-0000-000000000001",
    "date": "2022-06-02",
    "employeeName": "Joe Dough",
    "licensePlate": "abc-123"
}

###
PUT {{url}}/reservations/f649abd5-8934-44fe-85ce-ae1008c61b99
Content-Type: application/json

{
    "licensePlate": "123-123"
}


###
DELETE {{url}}/reservations/1
 