@url = http://localhost:5000



###


GET {{url}}/reservations

###


GET {{url}}/reservations/055de208-ba09-4398-84cc-8daac81b01f6

###

POST {{url}}/reservations
Content-Type: application/json

{
    "parkingSpotId": "00000000-0000-0000-0000-000000000001",
    "date": "2022-06-02",
    "employeeName": "Joe Dough",
    "licensePlate": "abc-123"
}

###
PUT {{url}}/reservations/055de208-ba09-4398-84cc-8daac81b01f6
Content-Type: application/json

{
    "licensePlate": "123-123"
}


###
DELETE {{url}}/reservations/1
 